### ISSUE TITLE
UnicodeDecodeError when saving heartbeat to offline cache

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime#112]
```
Traceback (most recent call last):
  File "/Users/user/.vscode/extensions/WakaTime.vscode-wakatime-1.1.21/out/wakatime-master/wakatime/main.py", line 66, in execute
    retval = send_heartbeats(heartbeats, args, configs)
  File "/Users/user/.vscode/extensions/WakaTime.vscode-wakatime-1.1.21/out/wakatime-master/wakatime/api.py", line 167, in send_heartbeats
    handle_result([heartbeats[i]], c, text, args, configs)
  File "/Users/user/.vscode/extensions/WakaTime.vscode-wakatime-1.1.21/out/wakatime-master/wakatime/api.py", line 198, in handle_result
    queue.push_many(h)
  File "/Users/user/.vscode/extensions/WakaTime.vscode-wakatime-1.1.21/out/wakatime-master/wakatime/offlinequeue.py", line 103, in push_many
    self.push(heartbeat)
  File "/Users/user/.vscode/extensions/WakaTime.vscode-wakatime-1.1.21/out/wakatime-master/wakatime/offlinequeue.py", line 57, in push
    'id': heartbeat.get_id(),
  File "/Users/user/.vscode/extensions/WakaTime.vscode-wakatime-1.1.21/out/wakatime-master/wakatime/heartbeat.py", line 162, in get_id
    h=self,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 95: ordinal not in range(128)
```

Heartbeat class should be able to serialize non-ascii files, project, and branch names.

**Comment by alanhamlett** [comment]
Fixed in v10.0.3.
