### ISSUE TITLE
Problem with python urllib/ssl and OpenSSL  0.9.8e

### ISSUE THREAD

**Issue by mclang** [wakatime/wakatime#15]
I just updated wakatime vim plugin to the one (3.0.7) where you can select used python version with "g:wakatime_PythonBinary" . I started to get a lot of these errors:
```
Traceback (most recent call last):
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime-cli.py", line 20, in <module>
    sys.exit(wakatime.main(sys.argv))
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/__init__.py", line 406, in main
    **vars(args)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/__init__.py", line 323, in send_heartbeat
    proxies=proxies)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/packages/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/packages/urllib3/connectionpool.py", line 326, in _make_request
    self._validate_conn(conn)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/packages/urllib3/connectionpool.py", line 740, in _validate_conn
    conn.connect()
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/packages/urllib3/util/ssl_.py", line 254, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/local/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/local/lib/python3.4/ssl.py", line 535, in __init__
    raise ValueError("check_hostname requires server_hostname, "
ValueError: check_hostname requires server_hostname, but it's not supported by your OpenSSL library
```
For some reason I don't get any errors when using version 3.0.6... Proper thing to do would propably be update my OpenSSL but alas, that is not possible because I'm running CentOS 5.

**Comment by mclang** [comment]
Sorry, this issue went into wrong place.
