### ISSUE TITLE
Error for config with missed option: submodules_disabled of git section

### ISSUE THREAD

**Issue by elipavlov** [wakatime/wakatime#152]
Got this kind of error on wakatime PyCharm plugin initialisation.

version of wakatime: 10.4.1

```python
Traceback (most recent call last):
  File "/pets/wakatime/wakatime/main.py", line 48, in execute
    hb = Heartbeat(vars(args), args, configs)
  File "/pets/wakatime/wakatime/heartbeat.py", line 100, in __init__
    project, branch = get_project_info(configs, self, data)
  File "/pets/wakatime/wakatime/project.py", line 81, in get_project_info
    if project.process():
  File "/pets/wakatime/wakatime/projects/git.py", line 31, in process
    return self._find_git_config_file(self.path)
  File "/pets/wakatime/wakatime/projects/git.py", line 68, in _find_git_config_file
    if self._submodules_supported_for_path(path):
  File "/pets/wakatime/wakatime/projects/git.py", line 90, in _submodules_supported_for_path
    if disabled.strip().lower() == 'true':
AttributeError: 'NoneType' object has no attribute 'strip'
```

I have tried to reproduce error on test case (See PR).

**Comment by alanhamlett** [comment]
Thanks for the test improvement! Fixed this bug in v10.4.2, so restarting PyCharm should upgrade your plugin to the latest wakatime-cli version including the fix.
