### ISSUE TITLE
Stuck on Initialization

### ISSUE THREAD

**Issue by AlphaKennyBudy** [wakatime/wakatime#217]
Everything did work fine until I installed wakatime on my WSL2 Ubuntu.

I am using vs code with WSL2 Ubuntu. Until today it tracked everything but now it tracks only my fish-shell..

That's what vs code dev mode shows me:
```
  ERR tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8080: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8080
    at ClientRequest.<anonymous> (/home/adil/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/dist/extension.js:226:108815)
    at Object.onceWrapper (events.js:288:20)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by gandarez** [comment]
Please copy and paste your `~/.wakatime.cfg` (don't forget to obfuscate your api_key).

**Comment by AlphaKennyBudy** [comment]
@gandarez 
```
[settings]
debug = true
api_key = __
hide_file_names = false
hide_project_names = false
hide_branch_names =
exclude =
    ^COMMIT_EDITMSG$
    ^TAG_EDITMSG$
    ^/var/(?!www/).*
    ^/etc/
include =
    .*
include_only_with_project_file = false
status_bar_icon = true
status_bar_coding_activity = true
offline = true
proxy = https://user:pass@localhost:8080
no_ssl_verify = false
ssl_certs_file =
timeout = 30
hostname = machinename
[projectmap]
projects/foo = new project name
^/home/user/projects/bar(\d+)/ = project{0}
[git]
disable_submodules = false

```

**Comment by gandarez** [comment]
@AlphaKennyBudy you shouldn't copy and paste the example from the website instead please use this version

```
[settings]
api_key = <your_api_key>
status_bar_icon = true
status_bar_coding_activity = true
```
