### ISSUE TITLE
Ask for help: How do I handle the problem with Wakatime plugin for vs

### ISSUE THREAD

**Issue by TheVeryDarkness** [wakatime/wakatime#245]
I've found the log file, but I can't really understand it. And It seems some native sentences occur in the log.
I use latest vs 2019 community 16.8.2. And I can use Wakatime correctly with vscode.

```
[WakaTime Debug 12:27:50 AM] Initializing async.
[WakaTime Info 12:27:51 AM] Initializing WakaTime v10.3.1
[WakaTime Debug 12:27:51 AM] Using standalone wakatime-cli.
[WakaTime Debug 12:27:51 AM] Downloading wakatime-cli...
[WakaTime Debug 12:27:51 AM] No proxy will be used. It's either not set or badly formatted.
[WakaTime HandledException 12:33:27 AM] Are you behind a proxy? Try setting a proxy in WakaTime Settings with format https://user:pass@host:port. Exception Traceback:: System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。. ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.WebClient.DownloadBitsState.RetrieveBytes(Int32& bytesRetrieved)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream, CompletionDelegate completionDelegate, AsyncOperation asyncOp)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at WakaTime.Shared.ExtensionUtils.Dependencies.DownloadAndInstallCli()
   at WakaTime.Shared.ExtensionUtils.WakaTime.InitializeAsync()
[WakaTime Info 12:33:27 AM] Finished initializing WakaTime v10.3.1
[WakaTime Debug 12:33:35 AM] ["D:\1853308\AppData\Roaming\WakaTime\wakatime-cli\wakatime-cli.exe", "--key", "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX4b48", "--entity", "D:\Project\pu\pu-cpp\typename.hpp", "--time", "1606408078.169380", "--plugin", "visualstudio/16.0 visualstudio-wakatime/10.3.1", "--category", "coding", "--project", "pu", "--extra-heartbeats"]
[WakaTime Debug 12:33:35 AM] 系统找不到指定的文件。
[WakaTime HandledException 12:33:35 AM] Could not send heartbeat.: 
[WakaTime HandledException 12:33:35 AM] 系统找不到指定的文件。: 
```

I translate it by Bing translator for you.

```
WakaTime Debug 12:27:50 AM Initializing async.
WakaTime Info 12:27:51 AM Initializing WakaTime v10.3.1
(WakaTime Debug 12:27:51 AM) Using standalone wakatime-cli.
(WakaTime Debug 12:27:51 AM) Downloading wakatime-cli...
(WakaTime Debug 12:27:51 AM) No proxy will be used. It's either not set or badly formatted.
WakaTime HandledException 12:33:27 AM Are you behind a proxy? Try set a proxy in WakaTime Settings with format https://user:pass@host:port. Exception Traceback:: System.Net.WebException: An exception evented when a WebClient request. ---> System.IO.IOException: Unable to read data from the transport connection: The remote host forced the closure of an existing connection. ---> System.Net.Sockets.SocketException: Remote hosts force an existing connection to be shut down.
   at System.Net.Sockets.Socket.Receive (Byte, Buffer, Int32 offset, Int32 size, Socket Flags socketFlags)
   at System.Net.Sockets.NetworkStream.Read (Byte.buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace---
   at System.Net.ConnectStream.Read (Byte, Int32 offset, Int32 size)
   at System.Net.WebClient.DownloadBitsState.Retrieve Bytes (Int32 and BytesRetrieved)
   at System.Net.WebClient.DownloadBits (WebRequest request, Stream writeStream, CompleteDelegate CompleteDelegate, AsyncOperation asyncOp)
   at System.Net.WebClient.DownloadFile (Uri address, String fileName)
   --- End of inner exception stack trace---
   at System.Net.WebClient.DownloadFile (Uri address, String fileName)
   at System.Net.WebClient.DownloadFile (String address, String fileName)
   at WakaTime.Shared.ExtensionUtils.Dependencies.DownloadAndInstallCli ()
   at WakaTime.Shared.ExtensionUtils.WakaTime.InitializeAsync ()
(WakaTime Info 12:33:27 AM) Finished initializing WakaTime v10.3.1
(WakaTime Debug 12:33:35 AM) ""D:-1853308"AppData?RoamingWakaTime?wakatime?wakatime-cli.exe", "-key", "XXXXXXXXXX-XXXXXXXX4b48", "-Entity", "D:Project-pu-pu-cpp.exe "-time," "1606408078.169380," "-plugin," "visualstudio/16.0 visualstudio-wakatime/10.3.1," "-category," "coding," "-project," "pu," "-extra-heartbeats"
The specified file could not be found by the system at 12:33:35 AM.
(WakaTime HandledException 12:33:35 AM) Can not send heartbeat:: 
The specified file could not be found by the system at 12:33:35 AM. : 
```

**Comment by alanhamlett** [comment]
That's a networking error. Do you need to set a proxy to connect to https://api.wakatime.com or https://wakatime-cli.s3-us-west-2.amazonaws.com?
