### ISSUE TITLE
Eclipse - Python not found but it is installed (linux)

### ISSUE THREAD

**Issue by Josee9988** [wakatime/wakatime#253]
![image](https://user-images.githubusercontent.com/38838976/107950117-99244280-6f96-11eb-94d4-a4e12ad1fb82.png)

![image](https://user-images.githubusercontent.com/38838976/107950182-a9d4b880-6f96-11eb-8e6b-6daf2f616a0b.png)

![image](https://user-images.githubusercontent.com/38838976/107950257-c40e9680-6f96-11eb-9d5f-764b2d45458d.png)

![image](https://user-images.githubusercontent.com/38838976/107950414-f7e9bc00-6f96-11eb-8406-83832c11d7c6.png)

---

**System information**
`uname -a` outputs:
`Linux joseumsi 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

I just installed eclipse and I would like to use wakatime, but this appears. I have python installed by default as I am using Ubuntu 20.04.

What should I do? Why is it not recognizing python by default.

Thanks

Eclipse logs: (Window -> Show View -> Error Log)
Error:
`java.lang.NullPointerException
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1090)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at com.wakatime.eclipse.plugin.Dependencies.isCLIOld(Dependencies.java:107)
	at com.wakatime.eclipse.plugin.WakaTime.checkCore(WakaTime.java:206)
	at com.wakatime.eclipse.plugin.WakaTime.access$0(WakaTime.java:201)
	at com.wakatime.eclipse.plugin.WakaTime$1.run(WakaTime.java:144)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5023)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4529)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)`

**Comment by Josee9988** [comment]
I could make it work by installing `sudo apt install python-is-python3` but I think Wakatime should handle this instead of making the user download/creating an alias/referencing python as the actual version.
