### ISSUE TITLE
__init__ has no 'main' attribute

### ISSUE THREAD

**Issue by ashgillman** [wakatime/wakatime#36]
I am having issues getting the CLI to run on Ubuntu 14.04

    $ wakatime
    wakatime
    Traceback (most recent call last):
      File "/usr/local/bin/wakatime", line 9, in <module>
        load_entry_point('wakatime==4.1.4', 'console_scripts', 'wakatime')()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2093, in load
        raise ImportError("%r has no %r attribute" % (entry,attr))
    ImportError: <module 'wakatime.__init__' from '/usr/local/lib/python2.7/dist-packages/wakatime/__init__.pyc'> has no 'main' attribute

    $ python --version
    python --version
    Python 2.7.6

I installed using `sudo pip install wakatime`.

Any help would be much appreciated.

**Comment by alanhamlett** [comment]
Sorry about that, renamed `main` to `execute` and forgot to update setup.py. It's fixed with v4.1.6 on pypi.

**Comment by ashgillman** [comment]
Thanks :)
