### ISSUE TITLE
Wrong python version

### ISSUE THREAD

**Issue by matthewdias** [wakatime/wakatime#88]
My wakatime seems to be using the wrong python version.

```
File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
```

Is there a way I can resolve this?

**Comment by alanhamlett** [comment]
Which editor and OS?

**Comment by matthewdias** [comment]
Atom on Mac

**Comment by alanhamlett** [comment]
Let's move this to the Atom repo. Can you create a new issue here, with the error message above and any errors from your Atom Console window too?
https://github.com/wakatime/atom-wakatime/issues/new

Turning on Debug mode in Atom -> Preferences -> Plugins -> wakatime -> Settings helps find more error messages.

**Comment by matthewdias** [comment]
I was getting the same issue with sublime text actually. Should I still move it there?

**Comment by alanhamlett** [comment]
No, we can leave it here in that case.

With Debug mode on, are there more messages in your Sublime Console Window, or Atom Developer Console?

**Comment by matthewdias** [comment]
full logs, afaict: 
```
[WakaTime] [DEBUG] [wakatime.coffee:458] pythonw /Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/cli.py --file /Users/Matthew/Dropbox/Development/web/bump/client/app/templates/components/post-view.hbs --plugin atom-wakatime/6.0.14 --write --lineno 17 --verbose --config /Users/Matthew/.wakatime.cfg --alternate-project client

/Users/Matthew/.atom/packages/wakatime/lib/logger.coffee:54 [WakaTime] [WARN] [wakatime.coffee:463] Traceback (most recent call last):
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/cli.py", line 31, in <module>
    import wakatime
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/__init__.py", line 17, in <module>
    from .main import execute
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/main.py", line 36, in <module>
    from .logger import setup_logging
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/logger.py", line 17, in <module>
    from .packages.requests.packages import urllib3
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "/Library/Python/2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/Library/Python/2.7/site-packages/cryptography/x509/base.py", line 14, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, ec, rsa
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
```

**Comment by alanhamlett** [comment]
Looks like a version of `pyparsing` that's incompatible with your version of `packaging`:

https://github.com/pypa/packaging/issues/91

Running this Terminal command should fix it:
`sudo pip install --upgrade pyparsing`

**Comment by matthewdias** [comment]
seems to actually be calling pythonw instead of python.

```
[WARN] [wakatime.coffee:484] Error: Command failed: pythonw /Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/cli.py --file /Users/Matthew/Dropbox/Development/web/bump/client/app/templates/components/post-view.hbs --plugin atom-wakatime/6.0.14 --lineno 17 --config /Users/Matthew/.wakatime.cfg --alternate-project client
Traceback (most recent call last):
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/cli.py", line 31, in <module>
    import wakatime
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/__init__.py", line 17, in <module>
    from .main import execute
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/main.py", line 36, in <module>
    from .logger import setup_logging
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/logger.py", line 17, in <module>
    from .packages.requests.packages import urllib3
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/Matthew/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "/Library/Python/2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/Library/Python/2.7/site-packages/cryptography/x509/base.py", line 14, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, ec, rsa
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
```

Is this a problem? I attempted to install pip with pythonw and got the same error.

```
pythonw ~/Downloads/get-pip.py                                                                                                                                                                         ⏎
Traceback (most recent call last):
  File "/Users/Matthew/Downloads/get-pip.py", line 20061, in <module>
    main()
  File "/Users/Matthew/Downloads/get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "/Users/Matthew/Downloads/get-pip.py", line 119, in bootstrap
    import setuptools  # noqa
  File "/Library/Python/2.7/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/Library/Python/2.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
```

**Comment by alanhamlett** [comment]
Looks like your system python is broken. To fix it, run this Terminal command:

```
sudo curl -o /Library/Python/2.7/site-packages/pyparsing.py https://sourceforge.net/p/pyparsing/code/HEAD/tree/tags/pyparsing_2.2.0/src/pyparsing.py?format=raw
```

That will manually install the latest `pyparsing` so you can install pip and other python libraries again.

**Comment by matthewdias** [comment]
Installed python, pip, and pyparsing fresh and its working now. Thanks!
